### ISSUE TITLE
applebot app_id:delete error

### ISSUE THREAD

**Issue by cactis** [clayallsopp/applebot#1]
```
applebot app_id:delete --username myemail --password mypassword --name myappname
```

will got an error:

```
{"normal_output":"- Wait for the login URL","event":"step_start","name":"Wait for the login URL"}:in `AppleBot': Unspecified AppleBot error occured (AppleBot::AppleBotError)
    from {"normal_output":"✔ Wait for the login URL","event":"step_complete","name":"Wait for the login URL"}:in `AppleBot'
    from {"normal_output":"- Fill the login form","event":"action_start","name":"Fill the login form"}:in `AppleBot'
    from {"normal_output":"✔ Fill the login form","event":"action_complete","name":"Fill the login form"}:in `AppleBot'
    from {"normal_output":"- Wait for the login to process","event":"step_start","name":"Wait for the login to process"}:in `AppleBot'
    from {"normal_output":"✔ Wait for the login to process","event":"step_complete","name":"Wait for the login to process"}:in `AppleBot'
    from {"normal_output":"- Open the action URL (https://developer.apple.com/account/ios/identifiers/bundle/bundleList.action)","event":"action_start","name":"Open the action URL (https://developer.apple.com/account/ios/identifiers/bundle/bundleList.action)"}:in `AppleBot'
    from {"normal_output":"✔ Wait for the action URL to load","event":"action_complete","name":"Wait for the action URL to load"}:in `AppleBot'
    from {"normal_output":"\u001b[37;41;1m[error]\u001b[0m [phantom] Error: could not find App Id","message":"\u001b[37;41;1m[error]\u001b[0m [phantom] Error: could not find App Id","event":"echo"}:in `AppleBot'
    from {"normal_output":"Error: could not find App Id","message":"Error: could not find App Id","event":"echo"}:in `AppleBot'
    from {"process_status":"#<Process::Status: pid 1038 exit 1>","thread":"#<Thread:0x007fc9029862a0 dead>"}:in `AppleBot'
    from /Volumes/Macintosh HD 2/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/applebot-0.0.1/lib/applebot/error.rb:86:in `for_output'
    from /Volumes/Macintosh HD 2/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/applebot-0.0.1/lib/applebot/shell.rb:18:in `block in command'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/open3.rb:217:in `popen_run'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/open3.rb:99:in `popen3'
    from /Volumes/Macintosh HD 2/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/applebot-0.0.1/lib/applebot/shell.rb:5:in `command'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/applebot-0.0.1/lib/applebot.rb:93:in `run_command'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/applebot-0.0.1/bin/applebot:63:in `block (4 levels) in <top (required)>'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/applebot-0.0.1/lib/applebot.rb:60:in `with_credentials'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/applebot-0.0.1/bin/applebot:62:in `block (3 levels) in <top (required)>'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.6/lib/commander/command.rb:180:in `call'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.6/lib/commander/command.rb:180:in `call'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.6/lib/commander/command.rb:155:in `run'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.6/lib/commander/runner.rb:422:in `run_active_command'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.6/lib/commander/runner.rb:82:in `run!'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.6/lib/commander/delegates.rb:8:in `run!'
    from /Users/ctslin/.rbenv/versions/2.0.0-p0/lib/ruby/gems/2.0.0/gems/commander-4.1.6/lib/commander/import.rb:10:in `block in <top (required)>'
```

**Comment by clayallsopp** [comment]
Hey, sorry about that! The documentation for `app_id:delete` [was incorrect](235bff5799c63815254c94cd27e99e14ed4bbf0d). You need to supply a `--app_id` parameter, not `--name` - try that and let me know!

I pushed version [0.0.2 to RubyGems](http://rubygems.org/gems/applebot), which fixes the doc:

```
$ applebot app_id:delete -h

  app_id:delete

  Usage: applebot app_id:delete [options]

  Delete App ID

  Options:
    --app_id VALUE       REQUIRED App bundle identifier
```
